sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

matrix:
  fast_finish: true
  include:
    - php: 7
    - php: hhvm
  allow_failures:
    - php: hhvm

install:
  - travis_retry composer install --no-interaction

script:
  - ./vendor/bin/phpunit --disallow-test-output